package net.awazone.awazoneproject.model.userService.awazoneUserRole;

public enum AwazoneUserAuthority {

    //USER AUTHORITIES
    USER,
    VIEW_USERS,
    COUNT_USER_BY_ID,
    COUNT_UNLOCKED_USER,
    COUNT_ENABLED_USER,
    GET_USER_BY_ID,
    GET_USER_BY_USERNAME,
    GET_USER_BY_EMAIL,
    GET_USER_BY_DOMAIN,
    UPDATE_USER_CONTACT,
    UPDATE_USER_ADDRESS,
    UPDATE_USER_DOMAIN,

    CREATE_ROLE,
    VIEW_ROLES,
    VIEW_AUTHORITIES,
    UPDATE_ROLE_NAME,
    DELETE_ROLE,
    UPDATE_ROLE_DESC,

    UPLOAD_DOCS,
    VIEW_DOCS,
    DELETE_DOCS,
    READ_KYC_STATUS,
    APPROVE_DOC,
    GET_DOC_BY_USERNAME,
    DELETE_DOC_BY_USERNAME,

    NATIONAL_ADMIN_CREATE,
    NATIONAL_ADMIN_EDIT,
    NATIONAL_ADMIN_UPDATE,
    NATIONAL_ADMIN_DELETE,
    NATIONAL_ADMIN_LIST,

    STATE_ADMIN_CREATE,
    STATE_ADMIN_EDIT,
    STATE_ADMIN_UPDATE,
    STATE_ADMIN_DELETE,
    STATE_ADMIN_LIST,

    LOCAL_ADMIN_CREATE,
    LOCAL_ADMIN_EDIT,
    LOCAL_ADMIN_UPDATE,
    LOCAL_ADMIN_DELETE,
    LOCAL_ADMIN_LIST,

    PARTNER_ADMIN_CREATE,
    PARTNER_ADMIN_EDIT,
    PARTNER_ADMIN_UPDATE,
    PARTNER_ADMIN_DELETE,
    PARTNER_ADMIN_LIST,

    ADMIN_CREATE,
    ADMIN_EDIT,
    ADMIN_UPDATE,
    ADMIN_DELETE,
    ADMIN_LIST,

    CUSTOMER_CREATE,
    CUSTOMER_LIST,
    CUSTOMER_VIEW,
    CUSTOMER_EDIT,
    CUSTOMER_DELETE,
    CUSTOMER_REQUEST,
    CUSTOMER_EXPIRED_SUBSCRIPTION,

    PAYMENT_GATEWAY_SETUP,
    PAYMENT_GATEWAY_CONFIG,
    PAYMENT_GATEWAY_ADD,

    DOMAIN_CREATE,
    DOMAIN_EDIT,
    DOMAIN_LIST,
    DOMAIN_DELETE,

    ORDER_CREATE,
    ORDER_EDIT,
    ORDER_DELETE,
    ORDER_LIST,
    ADMIN_ORDER_VIEW,
    CUSTOMER_ORDER_VIEW,

    PLAN_CREATE,
    PLAN_ADD,
    PLAN_EDIT,
    PLAN_SHOW,
    PLAN_UPDATE,
    PLAN_DELETE,
    PLAN_LIST,

    REPORT_VIEW,
    REPORT_DELETE,
    REPORT_EDIT,
    REPORT_LIST,

    ROLES_CREATE,
    ROLES_EDIT,
    ROLES_UPDATE,
    ROLES_DELETE,
    ROLES_LIST,

    UPLOADED_FILES_CONTROL,
    UPLOADED_FILES_DIRECTORY_CONTROL,
    PRODUCT_CONTROL,
    INVOICES_CONTROL,

    KYC_APPROVE,
    KYC_VIEW,
    KYC_REJECT,
    KYC_VERIFY,
    KYC_ADD,

    SMS_CREATE,
    SMS_DELETE,
    SMS_GATEWAY_EDIT,
    SMS_GATEWAY_CREATE,
    SMS_GATEWAY_ADD,
    SMS_GATEWAY_VIEW,
    SMS_GATEWAY_LIST,

    EMAIL_CREATE,
    EMAIL_DELETE,
    EMAIL_GATEWAY_EDIT,
    EMAIL_GATEWAY_CREATE,
    EMAIL_GATEWAY_ADD,
    EMAIL_GATEWAY_VIEW,
    EMAIL_GATEWAY_LIST,

    SITE_SETTINGS,
    MARKETING_TOOLS,

    USER_DOMAIN_EDIT
}
